# Generated by Django 2.0.2 on 2019-01-31 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userconf', '0004_auto_20190131_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 13, 34, 10, 115991, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
