# Generated by Django 2.0.2 on 2019-02-02 09:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20190202_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'ordering': ['-create_date'],
                'verbose_name': 'Комментарий к статье',
                'verbose_name_plural': 'Комментарии к статье',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 9, 39, 36, 16844, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 9, 39, 36, 12472, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
