# Generated by Django 2.0.2 on 2019-02-13 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190213_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_prod', models.IntegerField(default=0)),
                ('q_vote', models.IntegerField(default=0)),
                ('rating_result', models.IntegerField(default=0, help_text='рейтинг 0-5', verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 8, 53, 9, 231042, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
