# Generated by Django 2.0.2 on 2019-02-13 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190213_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Rating'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 8, 54, 2, 538606, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
