# Generated by Django 2.0.2 on 2019-01-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190117_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая сумма'),
        ),
    ]
