# Generated by Django 2.0.2 on 2019-02-09 13:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190202_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 13, 20, 42, 906418, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 13, 20, 42, 902246, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
