# Generated by Django 2.0.2 on 2019-02-13 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190213_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default='2019-02-13 08:49:22.883703+00', verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 8, 57, 15, 854014, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
