# Generated by Django 2.0.2 on 2019-02-09 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190209_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonym_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Анонимный ключ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 14, 27, 41, 59172, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 14, 27, 41, 54371, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
