# Generated by Django 2.0.2 on 2019-02-13 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190213_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 9, 0, 25, 16692, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
