# Generated by Django 2.0.2 on 2019-01-24 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190124_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 13, 27, 35, 556305, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Заказ выполнен'),
        ),
    ]
