# Generated by Django 2.0.2 on 2019-01-24 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190124_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 13, 45, 45, 245434, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
