# Generated by Django 2.0.2 on 2019-01-26 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190126_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(choices=[('Direct Bank Tranfer', 'Direct Bank Tranfer'), ('Check Payment', 'Check Payment'), ('Paypal', 'Paypal')], default='Direct Bank Tranfer', max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 26, 10, 3, 0, 520912, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 26, 10, 3, 0, 521967, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
