# Generated by Django 2.0.2 on 2019-01-26 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190126_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 26, 10, 40, 0, 337584, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 26, 10, 40, 0, 338693, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
