# Generated by Django 2.0.2 on 2019-01-27 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_auto_20190126_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('payment_method', models.CharField(choices=[('Direct Bank Tranfer', 'Direct Bank Tranfer'), ('Check Payment', 'Check Payment'), ('Paypal', 'Paypal')], default='Direct Bank Tranfer', max_length=50, verbose_name='Способ оплаты')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 1, 27, 13, 24, 26, 608205, tzinfo=utc), verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 13, 24, 26, 607181, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
