# Generated by Django 2.0.2 on 2019-01-27 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20190127_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile1',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 13, 55, 49, 729395, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
