# Generated by Django 2.0.2 on 2019-01-27 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20190127_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 15, 5, 59, 686424, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
