# Generated by Django 2.0.2 on 2019-01-27 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190127_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 15, 35, 24, 656827, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
