# Generated by Django 2.0.2 on 2019-01-31 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20190127_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 13, 18, 19, 523795, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
