# Generated by Django 2.0.2 on 2019-01-31 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20190131_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 15, 48, 26, 437512, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
