# Generated by Django 2.0.2 on 2019-02-01 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20190131_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_prod', models.IntegerField(default=0)),
                ('q_vote', models.IntegerField(default=0)),
                ('rating_result', models.IntegerField(default=0, help_text='рейтинг 0-5', verbose_name='рейтинг')),
            ],
            options={
                'verbose_name_plural': 'Рейтинги',
                'verbose_name': 'Рейтинг',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 18, 36, 43, 504206, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
