# Generated by Django 2.0.2 on 2019-02-01 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20190201_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vote',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Vote1', verbose_name='рейтинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 18, 38, 20, 848714, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
