# Generated by Django 2.0.2 on 2019-02-01 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20190201_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 18, 48, 50, 556226, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Vote1', verbose_name='рейтинг'),
        ),
    ]
