# Generated by Django 2.0.2 on 2019-02-01 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20190201_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote1',
            new_name='Rating',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 19, 15, 1, 9511, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
