# Generated by Django 2.0.2 on 2019-02-01 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20190201_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vote',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 19, 16, 26, 431647, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
